import { motion } from 'framer-motion'
import { ArrowUpRight, Download, Send } from 'lucide-react'
import { projects, skills, timeline, stats } from '../data/content'
const rise={initial:{opacity:0,y:24},animate:{opacity:1,y:0},transition:{duration:.65,ease:[.16,1,.3,1]}}
export const SectionTitle=({tag,title,copy})=><motion.div {...rise} className="section-title"><p className="eyebrow">{tag}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</motion.div>
export function AnimatedBackground(){return <><div className="grain"/><div className="aurora a-one"/><div className="aurora a-two"/></>}
export function Button({children,href='#',quiet=false}){return <a href={href} className={'button '+(quiet?'quiet':'')}>{children}<ArrowUpRight size={16}/></a>}
export function ProjectCards(){return <div className="projects-grid">{projects.map((project,i)=><motion.article {...rise} transition={{...rise.transition,delay:i*.09}} className="project-card glass" key={project.title}><div className="project-art" style={{'--project':project.color}}><i/><i/><i/></div><div><p>{project.type} <span>{project.year}</span></p><h3>{project.title}</h3><ArrowUpRight/></div></motion.article>)}</div>}
export function SkillCards(){return <div className="skill-grid">{skills.map((skill,i)=><motion.div {...rise} transition={{...rise.transition,delay:i*.035}} className="skill-card glass" key={skill}><b>{String(i+1).padStart(2,'0')}</b><span>{skill}</span></motion.div>)}</div>}
export function Timeline(){return <div className="timeline">{timeline.map((item,i)=><motion.article {...rise} transition={{...rise.transition,delay:i*.1}} key={item.year}><time>{item.year}</time><div><h3>{item.title}</h3><p>{item.copy}</p></div></motion.article>)}</div>}
export function TechStats(){return <div className="stats">{stats.map((stat,i)=><motion.div {...rise} transition={{...rise.transition,delay:i*.08}} className="stat glass" key={stat.label}><span>{stat.label}</span><strong>{stat.value}</strong><small>{stat.detail}</small></motion.div>)}</div>}
export function ContactForm(){return <form className="contact-form glass" onSubmit={e=>e.preventDefault()}><label>Name<input placeholder="What should I call you?"/></label><label>Email<input type="email" placeholder="Where can I reach you?"/></label><label>Project details<textarea rows="4" placeholder="Tell me a little about your idea..."/></label><button className="button" type="submit">Send inquiry <Send size={16}/></button></form>}
export function ResumeDownload(){return <a className="resume-download" href="/resume.pdf" download><Download/> Download résumé <small>PDF · 2.4 MB</small></a>}
